name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: "recursive"

      - name: Install Rust tools
        run: |
          rustup update --no-self-update stable
          rustup default stable
          rustup component add --toolchain stable clippy rustfmt

      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          bundler-cache: true

      - name: Lint
        run: bundle exec rake lint

      # Verify that licenses conform to the policy in rust/about.toml
      - name: Check licenses
        run: |
          cargo install cargo-about --features cli
          cargo about generate rust/about_templates --name about --manifest-path rust/Cargo.toml --workspace > THIRD_PARTY_LICENSES.html
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: ["3.3", "3.4", "4.0"]
    runs-on: ${{ matrix.os }}
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: "recursive"

      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Restore Rust compile cache
        id: rust-compile-cache-restore
        uses: actions/cache/restore@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rust/target
          key: ${{ runner.os }}-rust

      - name: Run Rust tests
        run: bundle exec rake cargo_test

      - name: Run Ruby tests
        run: bundle exec rake test

      - name: Run Rubydex linter
        if: matrix.os == 'ubuntu-latest' && matrix.ruby == '4.0'
        run: bundle exec rdx lint .

      - name: Save Rust compile cache
        id: rust-compile-cache-save
        uses: actions/cache/save@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rust/target
          key: ${{ steps.rust-compile-cache-restore.outputs.cache-primary-key }}
